# Generated by Django 3.2.8 on 2021-10-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0002_movieimage_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='MovieImage',
        ),
    ]
